title: Murray Steele
email: contact@murto.dev
description: >-
  I'm Murray Steele, a third year computer science student at The University of Edinburgh
baseurl: ""
url: "https://murto.dev"
github_username:  Murto

# Build settings
markdown: kramdown
theme: minima
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
